### ISSUE TITLE
Options to auto-assign identifiers

### ISSUE THREAD

**Issue by azaroth42** [gri-is/crom#8]
Easy options off the top of my head: Global integer, integer per URI segment, integer per class, UUID.
More complex options:  NOID service

Others that we could support?

**Comment by workergnome** [comment]
I've been trying to think of ways to make this sort of thing repeatable.  How do you maintain the identity across multiple builds, particularly as content changes?

**Comment by azaroth42** [comment]
Yes, replaying transformations is tricky. Incrementing integers can be replayed easily, or other algorithmically generated lists of identifiers. NOID I believe does this.

But the real challenge is when the model changes - if there are more objects, then replaying the list of IDs will be wrong. Or changing the semantics of a resource.

**Comment by workergnome** [comment]
I've been trying to think of a solution here for replay-ability (for art tracks, for persistent URIs for individual transactions).  In particular, is there a way to do so that uses a combination of content hashes and precedes/supercedes predicates.  I don't really want to go down the rabbit hole of PROV or something that strong, and this has to be done at the application level, but using a content hash, and then having the editing application track changes and provide them back for storage might be a possible way to do it.

Again, this is more of a artifact of the fact that I'm trying to store many dependent, mutable events in a single record, but it's the technique that I'm currently exploring.  The only other option I have is blank nodes, and I feel this is better than that.

**Comment by azaroth42** [comment]
I was going to suggest some sort of slug generator ... but when the id is currently assigned is when the object is created. So there's no additional properties or information to use to generate the slug. After instantiation, the URI is still changeable -- just modify the `id` property on the object. I think we close this issue for now, and open new ones if the current suite is insufficient or someone has a particular request?

**Comment by workergnome** [comment]
Sure.  At some point, it may be useful to build a 'ID from Content' function, but let's open that when it's needed.

Happy with closing this.
